218 italian localization is not shown
ham-radio-software/D-Rats pull request #225
Opened 2023-07-09 22:05 UTC by maurizioandreotti

2023-07-16 22:09 UTC, wb8tyw requested changes
Looks like a start, and there is a lot we need to understand, such as why the .glade file is being removed.

2023-07-16 22:09 UTC, wb8tyw commented on d_rats/version.py
> +AUTHORS = "Dan Smith, KK7DS \n" \
Just a note, have to make sure these tests do not break assumptions in the python packaging script that also use them.

2023-07-16 22:09 UTC, wb8tyw commented on ui/mainwindow.glade
Why is this file empty?

2023-07-16 22:09 UTC, wb8tyw commented on ui/mainwindow.glade.h
Hmm, if this is needed, for apparently we have not been keeping it up to date with the ui.mainwindow.glade file.
Maybe we are missing a step in building the pot.

The POT file either must be reading the.glade file or the .glade.h file.

2023-07-16 22:13 UTC, wb8tyw commented
I will try to find some time next week to so some testing of this PR.

2023-08-21 13:08 UTC, maurizioandreotti commented on d_rats/mainapp.py
> +        except Exception as error: # pylint: disable=broad-except
as you know i am not a programmer, so lack of experience. so i would need some advice here

in my local machine the code was working without needing these lines, but when i put it on github it started complaining and blocking the pr, so i had to add these exceptions to have the PR done

2023-08-21 13:13 UTC, maurizioandreotti commented on ui/mainwindow.glade
I see it with contents... maybe I did some errors in creating the Pr?

2023-08-22 13:38 UTC, wb8tyw commented on d_rats/version.py
> +          "Maurizio Andreotti IZ2LXI <maurizioandreotti lc@gmail.com>\n" \
Just noticed that there is a space in the e-mail address, which makes it invalid.

2023-09-18 13:31 UTC, wb8tyw commented
I have created a local branch based on this PR re-based to the current master for testing

2023-09-27 01:52 UTC, wb8tyw commented
Just a note here while I am working on a different version of this PR.

We can simplify a lot of the D-Rats code by using the python-pycountry debian module, with similar RPM module or the msys2 mingw-w64-python-pycountry module.

It allows D-Rats to just look at what message catalogs are available instead of us having to maintain a table of language codes and language names.

2023-10-22 07:43 UTC, closed without merging